function [outputArg1,outputArg2] = DisplayLegends(Curves,Nfig)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
 figure(Nfig);
 hold on;
if isstruct(Curves)
    A = legend(...
        'Poulaine gauche Initiale mise à l''échelle du modèle',...
        'Poulaine droite Initiale mise à l''échelle du modèle',...
        'Poulaine gauche Finale (sortie d''optimisation)',...
        'Poulaine droite Finale (sortie d''optimisation)',...
        'Poulaine droite d''entrée d''optimisation',...
        'Poulaine droite d''entrée d''optimisation',...
        '',...
        '',...
        '',...
        '',...
        '');
end

if size(Curves,2) == 6
    
    for i = 1:6
        
    end
    
     A = legend(...
        'Poulaine gauche Initiale mise à l''échelle du modèle',...
        'Poulaine droite Initiale mise à l''échelle du modèle',...
        'Poulaine gauche Finale (sortie d''optimisation)',...
        'Poulaine droite Finale (sortie d''optimisation)',...
        'Poulaine droite d''entrée d''optimisation',...
        'Poulaine droite d''entrée d''optimisation',...
        '',...
        '',...
        '',...
        '',...
        '');
    
    
elseif size(Curves,2) == 11
    
    


end

